CREATE TABLE tweet (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	tweet_id INTEGER, 
	tweet_text VARCHAR(1000), 
	province VARCHAR(1000), 
	age_groups VARCHAR(1000),  
	cities VARCHAR(1000),  
	"FSAs" VARCHAR(1000),  
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	UNIQUE (tweet_id)
);